function [headers,hashtags] = headerhashtag
  headers = {'Tweet count update from @realDonaldTrump';...
            'Back w/tweet stats @realDonaldTrump';...
            '.@realDonaldTrump''s continued tweet tantrum...';...
            'Peep these @realDonaldTrump tweet stats';...
            'Some @realDonaldTrump tweet stuffs';...
            'The sheer number of @realDonaldTrump tweets is ridiculous';...
            'The @realDonaldTrump tweet recap';...
            'Donny being Donny. @realDonaldTrump tweets away...';...
            '.@realDonaldTrump just can''t stop tweeting';...
            '.@realDonaldTrump won''t stop tweeting';...
            'Mr. 280 characters @realDonaldTrump';...
            'Depressing tweet stats from @realDonaldTrump';...
            'Twit tweet recap from @realDonaldTrump';...
            'Comrade @realDonaldTrump tweet stats';...
            'Lil @realDonaldTrump tweets again';...
            '.@realDonaldTrump tweeting more lies like a frantic man-child';...
            '.@realDonaldTrump tweeting like a guilty man';...
            'Name''s Donny & I tweet good @realDonaldTrump';...
            '"Tweetin''s my biznuss" -@realDonaldTrump';...
            'The idiot @realDonaldTrump tweeting again';...
            'Don the con at it again @realDonaldTrump';...
            'Ole @realDonaldTrump is tweetin scared';...
            '.@realDonaldTrump tweeting like a guilty man';...
            '.@realDonaldTrump just can''t stop tweeting';...
            'Nice disapproval rating @realDonaldTrump';...
            '.@realDonaldTrump pander-tweeting to the base'};

  hashtags = {'#nothingbettertodo';...
              '#tweeterinchief';...
              '#LilDonnyDumDum';...
              '#toilettweets';...
              '#morningpooptweets';...
              '#tweeterinchief';...
              '#donnytweets';...
              '#thisisamericanow';...
              '#MuellerTime';...
              '#basta';...
              '#TrumpResign';...
              '#TrumpResign #TrumpShutdown';...
              '#TrumpUnchained';...
              '#dumptrump';...
              '#fakenews';...
              '#TraitorTrump';...
              '#DumpTrump';...
              '#trumptrainwreck';...
              '#DonnyDontRead';...
              '#twitontwitter';...
              '#comradeDonny';...
              '#Trumptroll';...
              '#lockhimup';...
              '#DonnyUnhinged';...
              '#TrumpShutdown';...
              '#collusion';...
              '#LightTreason';...
              '#PutinsSub';...
              '#impeachtrump';...
              '#resist';...
              '#GOPeeTape';...
              '#fatDonny';...
              '#notawitchhunt';...
              '#donthecon';...
              '#MuellerAintGoingAway';...
              '#MakeAttorneysGetAttorneys'};
end
