function [a] = updatestatus(tw)
    header = {'Tweets from @realDonaldTrump';...
              'Back w/tweet stats @realDonaldTrump';...
              'Peep these @realDonaldTrump tweet stats';...
              'Some @realDonaldTrump tweet stuffs';...
              'The @realDonaldTrump tweet recap';...
              'Donny being Donny @realDonaldTrump';...
              '.@realDonaldTrump just can''t stop tweeting';...
              '.@realDonaldTrump won''t stop tweeting';...
              'Mr. 280 characters @realDonaldTrump';...
              'Depressing tweet stats from @realDonaldTrump';...
              'Twit tweet recap from @realDonaldTrump';...
              'Comrade @realDonaldTrump tweet stats';...
              'Lil @realDonaldTrump tweets again';...
	          '.@realDonaldTrump tweeting like a guilty man';...
              'Name''s Donny & I tweet good @realDonaldTrump';...
              '"Tweetin''s my biznuss" -@realDonaldTrump';...
              'The idiot @realDonaldTrump does it again';...
              'Don the con at it again @realDonaldTrump';...
              'Ole @realDonaldTrump is tweetin scared';...
              '.@realDonaldTrump tweeting like a guilty man';...
              '.@realDonaldTrump just can''t stop tweeting';...
              'Nice disapproval rating @realDonaldTrump';...
              '.@realDonaldTrump pander-tweeting to the base'};
              
    hashtags = {'#nothingbettertodo';'#tweeterinchief';'#LilDonnyDumDum';...
                '#toilettweets';'#morningpooptweets';'#tweeterinchief';...
                '#donnytweets';'#thisisamericanow';'#MuellerTime';...
                '#basta';'#BlueWave2018';'#TrumpUnchained';'#dumptrump';...
                '#fakenews';'#DumpTrump';'#LockerRoomTalk';...
                '#trumptrainwreck';'#TrumpOlympics';'#DonnyDontRead';...
                '#twitontwitter';'#comradeDonny';'#Trumptroll';...
                '#lockhimup';'#DonnyUnhinged';'#collusion';...
                '#VoteInNovember';'#LightTreason';'#PutinsSub';...
                '#impeachtrump';'#resist';'#GOPeeTape';'#fatDonny';...
                '#notawitchhunt';'#donthecon';'#MuellerAintGoingAway';...
                '#MakeAttorneysGetAttorneys'};

    b = fliplr(randperm(length(hashtags)));
    c = fliplr(randperm(length(header)));
    
    hashtags = hashtags(b);
    header   = header(c);
    
    a = {sprintf('%s\n',header{randperm(length(header),1)});...
         sprintf('Total (2018)         : %d\n',tw.data.tweetscnt);...
         sprintf('Original (no RTs) : %d\n',tw.data.originalcnt);...
         sprintf('Tweets/day          : %4.3f\n',tw.data.tperd);...
         sprintf('Proj. 2018 total    : %7.2f\n',tw.data.tproj);...
         sprintf(hashtags{randperm(length(hashtags),1)})};
     
%          a = {sprintf('%s\n',header{c(1)});...
%          sprintf('Total (2018)         : %d\n',tw.data.tweetscnt);...
%          sprintf('Original (no RTs) : %d\n',tw.data.originalcnt);...
%          sprintf('Tweets/day          : %4.3f\n',tw.data.tperd);...
%          sprintf('Proj. 2018 total    : %7.2f\n',tw.data.tproj);...
%          sprintf(hashtags{b(1)})};
end
